### ISSUE TITLE
CSRF token via HTTP header?

### ISSUE THREAD

**Issue by daniel-ac-martin** [UKHomeOffice/passports-form-wizard#36]
Am I right in thinking that the CSRF token can only be provided in the body / postdata of the request?

Would a PR adding functionality to accept the token via an HTTP header be welcome? ([csurf], for example provides this.)

This would allow us to support HTTP methods such as PATCH which is useful for AJAX requests.

 [csurf]: https://www.npmjs.com/package/csurf

**Comment by gavboulton** [comment]
The CSRF token is only currently added to the POST body. What would users without JS enabled get instead of PATCH?

**Comment by daniel-ac-martin** [comment]
It would still be the responsibility of the team building the form to make sure that there is provision for non-JS enabled users to edit the information they have entered. Of course, this would have to use a standard POST with he CSRF token in the POST body.

On top of that though, it would be nice to be able to offer JS-enabled users a better user experience by updating fields with PATCH which requires us to send in the CSRF token in another way.

What do you think @gavboulton?

Thanks again.

**Comment by gavboulton** [comment]
That sounds good to me.

**Comment by daniel-ac-martin** [comment]
Thanks. I'll submit a PR in due course!

**Comment by daniel-ac-martin** [comment]
#37
