### ISSUE TITLE
Whitelisting steps from journey history rather than the referrer

### ISSUE THREAD

**Issue by joeflintham** [UKHomeOffice/passports-form-wizard#38]
The backLinks option allows whitelisting of the referrer, but there may be scenarios in which we want to whitelist a step from earlier in the user's history. E.g. using the steps definition from test/middleware/spec.back-link.js, the user may have the following journey history (as listed in req.sessionModel):

['/step1'. '/step2', '/step3a', '/step4'] 

They have used the back link to return to step3a, but they no longer see a back link because:
- step3a is not listed as a 'next' step for any other steps so no step is surfaced as a previous step
- the referrer ('step4') is not (and shouldn't be) a valid back-link so setting backLinks has no effect
- although setting backLink is an option, there are scenarios in which step3a could be the destination step for more than one other earlier step.

I'd like to suggest that in the back-links middleware we add a final case where any steps which appear in the user's history and are whitelisted should be served as the backlink. Where more than one step appears in the history, the most recent should be used.

If there are no objections I'll follow this with a PR.

**Comment by gavboulton** [comment]
Unless I've misunderstood your issue then I think your case should already be handled.

I'll investigate.

**Comment by joeflintham** [comment]
Here's a unit test for back-links.js which reproduces my case:

    it('permits whitelisting of steps in history', function () {
        req.get.withArgs('referrer').returns('http://example.com/base/step4');
        req.sessionModel.set('steps', ['/step1', '/step2', '/step3a', '/step4']);
        controller.options.backLinks = ['step2'];
        backLinks('/step3a', controller, steps)(req, res, next);
        res.locals.backLink.should.equal('step2');
    });

**Comment by gavboulton** [comment]
In your example, how would the user get to "/step3a" in the first place?

**Comment by joeflintham** [comment]
e.g. the action of a custom controller or using the 'forks' option in the hof base-controller: https://github.com/UKHomeOffice/hof-controllers/blob/master/lib/base-controller.js

**Comment by gavboulton** [comment]
@easternbloc @JoeChapman What thought have you given to back links on forked journeys?

**Comment by joeflintham** [comment]
@gavboulton Aside from the hof's forked journey scenario, would your view be that a custom controller which introduces an 'orphaned' step with no 'automatic' back-link should also be responsible for fixing the back-link for that step?

Or to put it another way, is there a reason not to whitelist steps from 2+ steps back rather than just one step back (i.e. the referrer)?
