### ISSUE TITLE
Populating filesize validation messages from config

### ISSUE THREAD

**Issue by sassquad** [UKHomeOffice/passports-form-wizard#41]
If you have minimum and maximum configurable filesizes, there's currently no provision to push these through to validation messages.

If, for example, you upload a file that is too small or too large, you have to hardwire the filesizes into the message, as follows (this is a portion of default.json from a locales folder):

    "validation": {
        "filesize-small": "Sorry, the file size is too small. Please upload a file that's between 50k and 1mb",
        "filesize": "Sorry, the file size is too big. Please upload a file that's between 50k and 1mb"
    }

This is too brittle. I'd prefer to have something like the following:

    "validation": {
        "filesize-small": "Sorry, the file size is too small. Please upload a file that's between {{minimumUploadSize}} and {{maximumUploadSize}}.",
        "filesize": "Sorry, the file size is too big. Please upload a file that's between {{minimumUploadSize}} and {{maximumUploadSize}}.",
    }

These variables can be populated in the same manner as the minlength and maxlength properties. In this instance, both values are required in the same string.

Filesizes should count as an allowable method for validation, so it makes sense to be able to push through values from environmental variables.

**Comment by gavboulton** [comment]
Closed via #46.
