### ISSUE TITLE
Expose current step number and total steps taking forks into account

### ISSUE THREAD

**Issue by joefitter** [UKHomeOffice/passports-form-wizard#49]
We require step labels to be generated programatically for maintainability reasons - https://jira.digital.homeoffice.gov.uk/browse/GFM-22

The currentStep should take into account the step in relation to the stage in the journey - if a user reaches a point but then goes back to a previous step and takes a fork, this should be reflected by being 'inserted' in their overall journey.

The totalSteps should be the length from start to finish by following 'next' properties, the actual steps should be compared against this to take forks into account, these can either add to or subtract from the totalSteps

**Comment by gavboulton** [comment]
Showing *current step* of *total steps* will be very confusing for the user if it changes as forks are taken. If a service always has a fixed number of steps then this may be useful but I think this situation is very rare. It may be the case if a journey has very few steps but in this situation a step count would probably not be needed.
