### ISSUE TITLE
Pass route name to controller when initialised

### ISSUE THREAD

**Issue by joefitter** [UKHomeOffice/passports-form-wizard#57]
https://github.com/UKHomeOffice/passports-form-wizard/blob/master/lib/wizard.js#L45

The name of the route isn't passed to the controller when looping through steps. This means if we want to access the route within the controller we have to use `req.url` and strip `/edit` if present.

I suggest we extend options to include the route by adding `options.route = route` before the controller is initialised

**Comment by gavboulton** [comment]
This makes sense to me.
