### ISSUE TITLE
Split out controller and error class into separate module

### ISSUE THREAD

**Issue by daniel-ac-martin** [UKHomeOffice/passports-form-wizard#59]
Because there are quite a few cases in which we want to create 'controller' modules that build on top of the wizard's controller, notably [hof-controllers](https://github.com/UKHomeOffice/hof-controllers) but also [passports-date-controller](https://github.com/UKHomeOffice/passports-date-controller), it would be nice if the wizards controller and error class etc. were available in a separate module, e.g. hmpo-form-wizard-controller.

This would mean that these modules would not have to pull down the entire wizard when they only require the code in the controller.

[hof](https://github.com/UKHomeOffice/hof) + hof-controllers probably provides a decent pattern for doing this.

What do people think?

**Comment by JoeChapman** [comment]
Makes sense to me

**Comment by daniel-ac-martin** [comment]
@gavboulton: How do you feel about this?

**Comment by gavboulton** [comment]
Seems fine to me.
