### ISSUE TITLE
remove templatePath option - parent application should define this

### ISSUE THREAD

**Issue by joefitter** [UKHomeOffice/passports-form-wizard#69]
Default express view rendering should be used. Instead of the current pattern of `router.use(wizard)`, each journey should have its own `express()` instance rather than `router`, each with their own views directory set on the app instance. This way default view rendering behaviour can be taken advantage of and we wont need to override with templatePath.

**Comment by joefitter** [comment]
@gavboulton @JoeChapman @easternbloc what do you guys think of this? Obvs would be a breaking change but would help us split up larger applications as each could have its own views and template partials via express-partial-templates. In Express terms a journey with its own views etc would be a sub-app, not a router, however it could contain one or more routers

**Comment by gavboulton** [comment]
I don't quite follow how it will help with splitting up apps but I think the idea is fine and offers more flexibility.

Coping in @HughePaul and @oli-weighell2

**Comment by joefitter** [comment]
@gavboulton currently express-partial-templates takes all the files in app views dir and adds them to res.locals.partials - this is fine for one journey or simple apps, but doesn't offer enough flexibility IMO - I'd like every journey to be able to have access to a superset of global partials, common partials, and journey specific partials. This can be achieved by using an express app instead of router at a journey level, and tweaking the express-partial-templates lib slightly so as not to add core views to the list of partials
