### ISSUE TITLE
invalidating required fields doesn't invalidate the step that set them

### ISSUE THREAD

**Issue by HughePaul** [UKHomeOffice/passports-form-wizard#74]
- a user is prevented from moving forward from a step when a required field has not been set,
- check-progress invalidates fields based on the wizard step options when a field is changed,
- check-progress forces a user back to a step that has been missed out of a journey, based on the next links / forks,

But
- the user isn't forced back to a previous step in a journey that has a required field when that field is invalidated.

This means that a user could reach the last step, skip back an earlier step, fill a field that invalidates all the following steps' required fields, skip forward to the last step, and nothing checks that all the required fields are present.

I propose that the check-progress middleware also check that the visited steps have their required fields filled to count them as successfully visited. This could be an optional per step to allow steps to opt out of this check.

**Comment by gavboulton** [comment]
This makes sense to me. It would also affect back links. Would the back link go to the first invalidated page?

We also should think about how this will work across multiple wizards.

**Comment by HughePaul** [comment]
If you tried to go back onto an invalidated page you'd end up on the last valid page anyway, in the same way as if you had deep-linked to it
